packages:
  - packages/*

onlyBuiltDependencies:
  - canvas
  - esbuild
  - protobufjs
  - sharp
  - tree-sitter
  - unrs-resolver

overrides:
  '@babel/runtime@<7.26.10': '>=7.26.10'
  axios@>=1.0.0 <1.8.2: '>=1.8.2'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  esbuild@<=0.24.2: '>=0.25.0'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  tar-fs@>=2.0.0 <2.1.2: '>=2.1.2'
  tar-fs@>=2.0.0 <2.1.3: '>=2.1.3'
